var lang = {
    "he": {
        "headPartA": "להזמנת שולחן במסעדה מלא את הטופס ונמצא עבורך שולחן מתאים",
        "headPartB": "פרטי הלקוח הינם לצורך אישור ההזמנה בלבד.",
        "chooseDate": "בחירת תאריך",
        "hour": "שעה",
        "date": "תאריך",
        "firstName": "שם פרטי",
        "firstNameMandatory": "שדה שם פרטי - חובה",
        "lastName": "משפחה",
        "lastNameMandatory": "שדה שם משפחה - חובה",
        "email": "אימייל",
        "emailMandatory": "שדה אימייל - חובה",
        "cellPhone": "טלפון נייד",
        "cellPhoneMandatory": "שדה טלפון נייד - חובה",
        "areaCode": "קידומת",
        "numberDiners": "מספר סועדים",
        "smokingArea": "אזור עישון",
        "no": "לא",
        "yes": "כן",
        "neverMind": "לא משנה",
        "area": "אזור",
        "remarks": "הערות",
        "iWantads": "אני מעוניין לקבל מידע על מבצעים מהמסעדה",
        "clickatacle": "קליק א טייבל",
        "retaurantName": "שם המסעדה",
        "findaPlace": "מצא מקום",
        "doOrder": "בצע הזמנה",
        "backToStart": "חזור להתחלה",
        "markWillDoOurBest": "הערה: המסעדה אינה מתחייבת להקצות שולחן באיזור הנבחר אך תשתדל לעשות כן.",
        "dateFormatError": "התאריך לא תקני",
        "emailisMandatory": "שדה אימייל - חובה",
        // "emailIsWrong": "ערך דואר אלקטרוני אינו תקין",
        "canOrderFutureOnly": "ניתן להזמין לתאריך עתידי בלבד.",
        "selectLaterHour": "נא לבחור שעה מאוחרת יותר.",
        "fNameMandatory": "נא למלא שם פרטי.",
        "lNameMandatory": "נא למלא שם משפחה.",
        "emailIsWrong": "נא למלא כתובת מייל תקינה.",
        "phoneNumbersOnly": "נא למלא מספרים בלבד, ללא קידומת",
        "msgFillRedFields": "אנא מלאו את השדות המסומנים באדום.",
        "orderSuccess": "ההזמנה בוצעה בהצלחה",
        "orderDate": "תאריך ההזמנה",
        "orderArea": "אזור במסעדה",
        "orderName": "הזמנה על שם",
        "orderCount": "כמות הסועדים",
        "restaurantEt": "מסעדת",
        "address": "כתובת",
        "restaurantPhone": "טלפון במסעדה",
        "msgNotYetApproved": "בקשתך להזמנת מקום התקבלה בהצלחה אך טרם אושרה",
        "requestRequest": "תאריך הבקשה",
        "requestName": "בקשה על שם",
        "errTooMuchRequests": "עברת את מכסת ההזמנות",
        "backToDate": "חזור לבחירת תאריך",
        "back": "חזרה",
        "forward": "קדימה",
        "orderTable": "הזמן שולחן"
    },
    "en": {
        "headPartA": "Head A",
        "headPartB": "Head B",
        "chooseDate": "Choose Date",
        "hour": "Hour",
        "date": "Date",
        "firstName": "First Name",
        "firstNameMandatory": "Please Fill Your Name",
        "lastName": "Last Name",
        "lastNameMandatory": "Please Fill Your Last Name",
        "email": "Email",
        "emailMandatory": "Please Fill Your Email",
        "cellPhone": "Cell Phone",
        "cellPhoneMandatory": "Please Fill Your Phone",
        "areaCode": "Area Code",
        "numberDiners": "Party Size",
        "smokingArea": "Smoking Area",
        "no": "no",
        "yes": "yes",
        "neverMind": "Never Mind",
        "area": "area",
        "remarks": "remarks",
        "iWantads": "I Demened Ads",
        "clickatacle": "Click A Table",
        "retaurantName": "Restaurant Name",
        "findaPlace": "Find a Place",
        "doOrder": "Do Order",
        "backToStart": "Back To Start",
        "markWillDoOurBest": "We will do our best.",
        "dateFormatError": "Must",
        "emailisMandatory": "Must",
        "canOrderFutureOnly": "ניתן להזמין לתאריך עתידי בלבד.",
        "selectLaterHour": "נא לבחור שעה מאוחרת יותר.",
        "fNameMandatory": "נא למלא שם פרטי.",
        "lNameMandatory": "נא למלא שם משפחה.",
        "emailIsWrong": "נא למלא כתובת מייל תקינה.",
        "phoneNumbersOnly": "נא למלא מספרים בלבד, ללא קידומת",
        "msgFillRedFields": "אנא מלאו את השדות המסומנים באדום.",
        "orderSuccess": "ההזמנה בוצעה בהצלחה",
        "orderDate": "תאריך ההזמנה",
        "orderArea": "אזור במסעדה",
        "orderName": "הזמנה על שם",
        "orderCount": "כמות הסועדים",
        "restaurantEt": "מסעדת",
        "address": "כתובת",
        "restaurantPhone": "טלפון במסעדה",
        "msgNotYetApproved": "בקשתך להזמנת מקום התקבלה בהצלחה אך טרם אושרה",
        "requestRequest": "Date request",
        "requestName": "Check Name",
        "errTooMuchRequests": "Avarta Et Hahazmana",
        "backToDate": "Back to Date",
        "back": "Back",
        "forward": "Forward",
        "orderTable": "Order a Table"
    }
};